import { Test, TestingModule } from '@nestjs/testing';
import { ConflictException, NotFoundException } from '@nestjs/common';
import { TimesheetsService } from './timesheets.service';
import { PrismaService } from '../../common/prisma/prisma.service';
import { NotificationsService } from '../notifications/notifications.service';
import { ApprovalsService } from '../approvals/approvals.service';
import { DepartmentScopeService } from '../../common/scoping/department-scope.service';
import { StorageService } from '../storage/storage.service';
import { OrgTimeZoneService } from '../../common/time/org-time-zone.service';
import { AuthPrincipal } from '../../common/decorators';
import { defaultPeriodCutoff } from '../payroll/payroll-period.scheduler';

/**
 * BUG-BL — the employee picks the payroll period their timesheet is routed to,
 * instead of it being fixed to the current calendar period.
 * BUG-BM — a submission after the period's cutoff is accepted and flagged, and
 * the period it was routed to is never rewritten to the current one.
 */

const principal = {
  userId: 'user-1',
  tenantId: 'tenant-1',
  organizationId: 'org-1',
  permissions: [],
  roles: ['EMPLOYEE'],
} as unknown as AuthPrincipal;

const JULY = {
  id: 'period-july',
  tenantId: 'tenant-1',
  organizationId: 'org-1',
  status: 'OPEN',
  type: 'FIRST_HALF',
  startDate: new Date('2026-07-01T00:00:00Z'),
  endDate: new Date('2026-07-15T00:00:00Z'),
  cutoffDate: new Date('2026-07-16T23:59:59.999Z'),
  lockedAt: null,
  name: null,
};

/** Builds TimesheetsService over a mock Prisma, returning both for assertions. */
async function buildService(prismaOverrides: Record<string, unknown> = {}) {
  const prisma = {
    payrollPeriod: {
      findFirst: jest.fn().mockResolvedValue(JULY),
      findMany: jest.fn().mockResolvedValue([JULY]),
    },
    timesheet: {
      findFirst: jest.fn().mockResolvedValue(null),
      create: jest.fn(async ({ data }: { data: Record<string, unknown> }) => ({
        id: 'ts-new',
        ...data,
      })),
      update: jest.fn(async ({ data }: { data: Record<string, unknown> }) => ({
        id: 'ts-1',
        ...data,
      })),
      findMany: jest.fn().mockResolvedValue([]),
    },
    timeEntry: {
      updateMany: jest.fn().mockResolvedValue({ count: 0 }),
      aggregate: jest.fn().mockResolvedValue({ _sum: { durationMinutes: 480 } }),
    },
    user: { findFirst: jest.fn().mockResolvedValue({ supervisorId: null }) },
    ...prismaOverrides,
  };

  const module: TestingModule = await Test.createTestingModule({
    providers: [
      TimesheetsService,
      { provide: PrismaService, useValue: prisma },
      { provide: NotificationsService, useValue: { create: jest.fn() } },
      { provide: ApprovalsService, useValue: { decide: jest.fn() } },
      { provide: DepartmentScopeService, useValue: { userIdsForDepartment: jest.fn() } },
      { provide: StorageService, useValue: { signedUrl: jest.fn() } },
      { provide: OrgTimeZoneService, useValue: { forPrincipal: jest.fn().mockResolvedValue('Asia/Manila') } },
    ],
  }).compile();

  return { service: module.get(TimesheetsService), prisma };
}

/** A DRAFT sheet owned by `principal`, overridable per case. */
function draft(overrides: Record<string, unknown> = {}) {
  return {
    id: 'ts-1',
    tenantId: 'tenant-1',
    organizationId: 'org-1',
    userId: 'user-1',
    status: 'DRAFT',
    periodStart: new Date('2026-07-01T00:00:00Z'),
    periodEnd: new Date('2026-07-15T00:00:00Z'),
    payrollPeriodId: null,
    isLateSubmission: false,
    summary: null,
    version: 0,
    deletedAt: null,
    ...overrides,
  };
}

// ── BUG-BL: the dropdown's options (verify steps b, c) ───────────────────────

describe('BUG-BL — selectablePayrollPeriods offers open periods and hides locked ones', () => {
  it('queries only OPEN / GENERATED periods with no lock stamp', async () => {
    const findMany = jest.fn().mockResolvedValue([]);
    const { service } = await buildService({
      payrollPeriod: { findMany, findFirst: jest.fn() },
    });

    await service.selectablePayrollPeriods(principal);

    const where = findMany.mock.calls[0][0].where;
    // Verify step (c): LOCKED and EXPORTED are absent, so they can never be picked.
    expect(where.status).toEqual({ in: ['OPEN', 'GENERATED'] });
    expect(where.lockedAt).toBeNull();
    expect(where.organizationId).toBe('org-1');
  });

  it('includes custom off-cycle periods — the filter is on status, not on isAutoGenerated', async () => {
    const findMany = jest.fn().mockResolvedValue([]);
    const { service } = await buildService({
      payrollPeriod: { findMany, findFirst: jest.fn() },
    });

    await service.selectablePayrollPeriods(principal);

    expect(findMany.mock.calls[0][0].where).not.toHaveProperty('isAutoGenerated');
  });

  it('marks a period whose cutoff has already passed, without excluding it', async () => {
    const { service } = await buildService({
      payrollPeriod: {
        findFirst: jest.fn(),
        findMany: jest.fn().mockResolvedValue([
          { ...JULY, cutoffDate: new Date('2000-01-01T00:00:00Z') },
        ]),
      },
    });

    const [period] = await service.selectablePayrollPeriods(principal);

    expect(period.pastCutoff).toBe(true);
    expect(period.id).toBe('period-july');
  });
});

// ── BUG-BL: the selected period drives the link (verify steps d, e, f) ───────

describe('BUG-BL — the selected period is what the timesheet is linked to', () => {
  it('stores the chosen payrollPeriodId when the draft is created', async () => {
    const { service, prisma } = await buildService();

    await service.create(principal, {
      periodStart: '2026-07-01',
      periodEnd: '2026-07-15',
      payrollPeriodId: 'period-july',
    });

    expect((prisma.timesheet.create as jest.Mock).mock.calls[0][0].data.payrollPeriodId).toBe(
      'period-july',
    );
  });

  it('links the chosen period on submit (verify step f)', async () => {
    const { service, prisma } = await buildService({
      timesheet: {
        findFirst: jest.fn().mockResolvedValue(draft()),
        update: jest.fn(async ({ data }: { data: Record<string, unknown> }) => data),
      },
    });

    await service.submit(principal, 'ts-1', { version: 0, payrollPeriodId: 'period-july' });

    const data = (prisma.timesheet.update as jest.Mock).mock.calls[0][0].data;
    expect(data.payrollPeriodId).toBe('period-july');
  });

  it('refuses a locked period rather than silently routing work into it', async () => {
    const { service } = await buildService({
      payrollPeriod: {
        findFirst: jest.fn().mockResolvedValue({ ...JULY, status: 'LOCKED', lockedAt: new Date() }),
        findMany: jest.fn(),
      },
      timesheet: {
        findFirst: jest.fn().mockResolvedValue(draft()),
        update: jest.fn(),
      },
    });

    await expect(
      service.submit(principal, 'ts-1', { version: 0, payrollPeriodId: 'period-july' }),
    ).rejects.toBeInstanceOf(ConflictException);
  });

  it('rejects a period id from another organization', async () => {
    const { service } = await buildService({
      payrollPeriod: { findFirst: jest.fn().mockResolvedValue(null), findMany: jest.fn() },
    });

    await expect(
      service.create(principal, {
        periodStart: '2026-07-01',
        periodEnd: '2026-07-15',
        payrollPeriodId: 'period-elsewhere',
      }),
    ).rejects.toBeInstanceOf(NotFoundException);
  });

  it('leaves the link unset when no period is chosen (frontline auto-assignment path)', async () => {
    const { service, prisma } = await buildService();

    await service.create(principal, { periodStart: '2026-07-01', periodEnd: '2026-07-15' });

    expect((prisma.timesheet.create as jest.Mock).mock.calls[0][0].data.payrollPeriodId).toBeNull();
  });
});

// ── BUG-BM: late flag and period pinning (verify steps b, c, d) ──────────────

describe('BUG-BM — submissions past the cutoff are flagged, not blocked', () => {
  /** Submits a DRAFT against JULY at `at`, returning the persisted update data. */
  async function submitAt(at: string, sheetOverrides: Record<string, unknown> = {}) {
    jest.useFakeTimers().setSystemTime(new Date(at));
    try {
      const { service, prisma } = await buildService({
        timesheet: {
          findFirst: jest.fn().mockResolvedValue(draft(sheetOverrides)),
          update: jest.fn(async ({ data }: { data: Record<string, unknown> }) => data),
        },
      });
      await service.submit(principal, 'ts-1', { version: 0, payrollPeriodId: 'period-july' });
      return (prisma.timesheet.update as jest.Mock).mock.calls[0][0].data;
    } finally {
      jest.useRealTimers();
    }
  }

  it('accepts a submission after the cutoff and flags it late (verify steps b, c)', async () => {
    const data = await submitAt('2026-07-20T09:00:00Z');

    expect(data.status).toBe('SUBMITTED');
    expect(data.isLateSubmission).toBe(true);
  });

  it('does not flag an on-time submission', async () => {
    const data = await submitAt('2026-07-16T09:00:00Z');

    expect(data.isLateSubmission).toBe(false);
  });

  it('keeps a late sheet on the period it was routed to, not the current one (verify step d)', async () => {
    const data = await submitAt('2026-07-20T09:00:00Z');

    expect(data.payrollPeriodId).toBe('period-july');
  });

  it('ignores a period change on a REJECTED resubmit — the original link survives', async () => {
    const { service, prisma } = await buildService({
      timesheet: {
        findFirst: jest
          .fn()
          .mockResolvedValue(draft({ status: 'REJECTED', payrollPeriodId: 'period-july' })),
        update: jest.fn(async ({ data }: { data: Record<string, unknown> }) => data),
      },
    });

    await service.submit(principal, 'ts-1', { version: 0, payrollPeriodId: 'period-august' });

    const data = (prisma.timesheet.update as jest.Mock).mock.calls[0][0].data;
    expect(data.payrollPeriodId).toBe('period-july');
  });

  it('leaves the flag alone when no period is linked — there is no cutoff to judge', async () => {
    const { service, prisma } = await buildService({
      timesheet: {
        findFirst: jest.fn().mockResolvedValue(draft()),
        update: jest.fn(async ({ data }: { data: Record<string, unknown> }) => data),
      },
    });

    await service.submit(principal, 'ts-1', { version: 0 });

    expect((prisma.timesheet.update as jest.Mock).mock.calls[0][0].data.isLateSubmission).toBe(false);
  });
});

// ── BUG-BM: Finance's late-only filter (verify step e) ───────────────────────

describe('BUG-BM — hrFindAll filters on the late flag', () => {
  it('narrows to late submissions when lateOnly=true', async () => {
    const findMany = jest.fn().mockResolvedValue([]);
    const { service } = await buildService({
      timesheet: { findMany, findFirst: jest.fn() },
    });

    await service.hrFindAll(principal, { lateOnly: 'true' });

    expect(findMany.mock.calls[0][0].where.isLateSubmission).toBe(true);
  });

  it('returns every timesheet when the filter is omitted', async () => {
    const findMany = jest.fn().mockResolvedValue([]);
    const { service } = await buildService({
      timesheet: { findMany, findFirst: jest.fn() },
    });

    await service.hrFindAll(principal, {});

    expect(findMany.mock.calls[0][0].where).not.toHaveProperty('isLateSubmission');
  });
});

// ── BUG-BM: every period gets a cutoff (verify step a) ──────────────────────

describe('BUG-BM — defaultPeriodCutoff gives every period a deadline', () => {
  it('falls at the end of the day after endDate — one day of grace', () => {
    expect(defaultPeriodCutoff(new Date('2026-07-15T00:00:00Z'))).toEqual(
      new Date('2026-07-16T23:59:59.999Z'),
    );
  });

  it('a last-day evening submission is on time, the next-next day is late', () => {
    const cutoff = defaultPeriodCutoff(new Date('2026-07-15T00:00:00Z'));

    expect(new Date('2026-07-15T22:00:00Z') > cutoff).toBe(false);
    expect(new Date('2026-07-17T00:00:00Z') > cutoff).toBe(true);
  });
});
