import { IsBoolean, IsEnum, IsInt, IsNumber, IsOptional, IsString, IsUUID, Max, Min } from 'class-validator';
import { Type } from 'class-transformer';
import { DeMinimisType, PayrollPeriodType } from '@prisma/client';

export class CreatePayrollPeriodDto {
  @IsEnum(PayrollPeriodType)
  type!: PayrollPeriodType;

  /** ISO date string, e.g. "2026-06-01" */
  @IsString()
  startDate!: string;

  /** ISO date string, e.g. "2026-06-15" */
  @IsString()
  endDate!: string;
}

export class GeneratePayrollDto {
  /**
   * Marks the run as a 13th-month payout, so the tax-exempt portion (up to the
   * org's `thirteenthMonthExemptionCap`) is excluded from taxable income and no
   * SSS/PhilHealth/Pag-IBIG is assessed on it. Optional — omitted means a
   * regular run, which is the pre-FEAT-3 behaviour.
   */
  @IsBoolean()
  @IsOptional()
  thirteenthMonth?: boolean;
}

export class ExportPayrollDto {
  @IsEnum(['PDF', 'XLSX', 'BOTH'])
  format!: 'PDF' | 'XLSX' | 'BOTH';
}

export class RunActionDto {
  @IsEnum(['generate', 'approve'])
  action!: 'generate' | 'approve';

  @IsUUID()
  periodId!: string;
}

export class PayrollExportRequestDto {
  @IsEnum(['PDF', 'CSV', 'XLSX'])
  format!: 'PDF' | 'CSV' | 'XLSX';

  @IsUUID()
  @IsOptional()
  periodId?: string;
}

export interface PayrollPeriodQuery {
  limit?: string;
  cursor?: string;
  status?: string;
  /** BUG-AX: "true" = only system-generated semi-monthly periods, "false" = only
   *  off-cycle custom periods. Omitted returns both. */
  isAutoGenerated?: string;
}

import { CompensationType } from '@prisma/client';

export class UpdateRateDto {
  @IsEnum(CompensationType)
  @IsOptional()
  compensationType?: CompensationType;

  @IsNumber()
  @Min(0)
  @IsOptional()
  rate?: number;

  @IsNumber()
  @Min(0)
  @IsOptional()
  hourlyRate?: number;

  @IsNumber()
  @Min(0)
  @IsOptional()
  dailyRate?: number;

  @IsNumber()
  @Min(1)
  @IsOptional()
  daysPerWeek?: number;

  @IsInt()
  @IsOptional()
  version?: number;
}

export class RejectPayrollDto {
  @IsString()
  reason!: string;
}

// -- Finance Payroll Processing (validate/approve/reject/send-to-bank pipeline) --

export class PayrollActionDto {
  @IsUUID()
  periodId!: string;
}

// -- FEAT-3: statutory contribution settings --

/**
 * Every field optional — the admin screen PATCHes only what changed. Rate bounds
 * are deliberately generous (a rate is a fraction, a peso cap is not) but reject
 * the two mistakes that actually happen: a percentage entered as `5` instead of
 * `0.05`, and a negative value.
 */
export class UpdatePayrollSettingsDto {
  @IsNumber() @Min(0) @Max(1) @IsOptional() sssEmployeeRate?: number;
  @IsNumber() @Min(0) @Max(1) @IsOptional() sssEmployerRate?: number;
  @IsNumber() @Min(0) @IsOptional() sssSalaryCeiling?: number;

  @IsNumber() @Min(0) @Max(1) @IsOptional() philhealthEmployeeRate?: number;
  @IsNumber() @Min(0) @Max(1) @IsOptional() philhealthEmployerRate?: number;
  @IsNumber() @Min(0) @IsOptional() philhealthMin?: number;
  @IsNumber() @Min(0) @IsOptional() philhealthMax?: number;

  @IsNumber() @Min(0) @Max(1) @IsOptional() pagibigEmployeeRateLow?: number;
  @IsNumber() @Min(0) @Max(1) @IsOptional() pagibigEmployeeRateHigh?: number;
  @IsNumber() @Min(0) @Max(1) @IsOptional() pagibigEmployerRate?: number;
  @IsNumber() @Min(0) @IsOptional() pagibigSalaryThreshold?: number;
  @IsNumber() @Min(0) @IsOptional() pagibigEmployeeCap?: number;

  @IsNumber() @Min(1) @Max(3) @IsOptional() nightShiftPremium?: number;
  @IsInt() @Min(0) @Max(23) @IsOptional() nightShiftStartHour?: number;
  @IsInt() @Min(0) @Max(23) @IsOptional() nightShiftEndHour?: number;

  @IsNumber() @Min(0) @Max(5) @IsOptional() regularHolidayWorkedRate?: number;
  @IsNumber() @Min(0) @Max(5) @IsOptional() regularHolidayUnworkedRate?: number;
  @IsNumber() @Min(0) @Max(5) @IsOptional() specialHolidayWorkedRate?: number;

  @IsNumber() @Min(0) @IsOptional() thirteenthMonthExemptionCap?: number;

  @IsInt() @Min(2018) @Max(2100) @IsOptional() birTaxTableYear?: number;
}

export interface StatutoryReportQuery {
  /** Payroll period to report on. Defaults to the most recently generated period. */
  periodId?: string;
}

/** BUG-AZ — query for the downloadable agency collection list. */
export class StatutoryExportQuery {
  /** Payroll period to report on. Defaults to the most recently generated period. */
  @IsUUID() @IsOptional() periodId?: string;

  /** Department *name*, matching the value the JSON report returns per row. */
  @IsString() @IsOptional() departmentId?: string;

  /** Defaults to CSV — every agency portal accepts it, Excel is a convenience. */
  @IsEnum(['csv', 'xlsx']) @IsOptional() format?: 'csv' | 'xlsx';
}

export class PayrollRejectActionDto {
  @IsUUID()
  periodId!: string;

  @IsString()
  reason!: string;
}

// ─── BUG-BC: Compensation & Benefits ────────────────────────────────────────

/** Query for the 13th-month YTD basic-salary tracker. */
export class ThirteenthMonthQuery {
  /** Tax year to aggregate. Defaults to the current calendar year. */
  @Type(() => Number) @IsInt() @Min(2018) @Max(2100) @IsOptional() year?: number;

  /** Narrow to one employee. Omitted returns the whole organisation. */
  @IsUUID() @IsOptional() employeeId?: string;
}

/**
 * Assign or amend a de minimis benefit. `monthlyAmount` is what HR intends to
 * pay; anything above the BIR ceiling for the type is clamped server-side and
 * reported back via `wasCapped` rather than rejected, because the excess is
 * simply taxable compensation rather than an invalid entry.
 */
export class AssignDeMinimisDto {
  @IsUUID() employeeId!: string;

  @IsEnum(DeMinimisType) benefitType!: DeMinimisType;

  @IsNumber() @Min(0) monthlyAmount!: number;

  @IsBoolean() @IsOptional() isActive?: boolean;

  @IsString() @IsOptional() notes?: string;
}

/** Query for listing de minimis assignments. */
export class DeMinimisQuery {
  @IsUUID() @IsOptional() employeeId?: string;
}
