import { Injectable, Logger } from '@nestjs/common';
import { Cron } from '@nestjs/schedule';
import { PrismaService } from '../../common/prisma/prisma.service';

/**
 * BUG-AJ: Auto-generates semi-monthly payroll periods (1st–15th and 16th–EOM)
 * for every active organization on the 1st and 16th of each month.
 *
 * Idempotent: skips creation if an overlapping period for the same
 * (tenantId, organizationId, startDate, endDate) already exists.
 *
 * Runs on the 1st   → generates FIRST_HALF  for current month + FIRST_HALF  for next month.
 * Runs on the 16th  → generates SECOND_HALF for current month + SECOND_HALF for next month.
 *
 * Generating one extra month ahead means the period dropdown always has
 * upcoming periods ready before the 1st/16th triggers.
 */
@Injectable()
export class PayrollPeriodScheduler {
  private readonly logger = new Logger(PayrollPeriodScheduler.name);

  constructor(private readonly prisma: PrismaService) {}

  // ── 1st of every month — generate FIRST_HALF periods ──────────────────────

  @Cron('0 0 1 * *', { name: 'auto-gen-first-half-periods', timeZone: 'Asia/Manila' })
  async generateFirstHalfPeriods() {
    const now = new Date();
    this.logger.log('Running FIRST_HALF period auto-generation...');

    const months = [
      { year: now.getFullYear(), month: now.getMonth() },       // current month
      monthOffset(now.getFullYear(), now.getMonth(), 1),        // next month
    ];

    for (const { year, month } of months) {
      await this.generateForAllOrgs('FIRST_HALF', year, month);
    }

    this.logger.log('FIRST_HALF period auto-generation complete.');
  }

  // ── 16th of every month — generate SECOND_HALF periods ────────────────────

  @Cron('0 0 16 * *', { name: 'auto-gen-second-half-periods', timeZone: 'Asia/Manila' })
  async generateSecondHalfPeriods() {
    const now = new Date();
    this.logger.log('Running SECOND_HALF period auto-generation...');

    const months = [
      { year: now.getFullYear(), month: now.getMonth() },
      monthOffset(now.getFullYear(), now.getMonth(), 1),
    ];

    for (const { year, month } of months) {
      await this.generateForAllOrgs('SECOND_HALF', year, month);
    }

    this.logger.log('SECOND_HALF period auto-generation complete.');
  }

  // ── Manual trigger (callable from a controller for testing) ───────────────

  /**
   * Generates both FIRST_HALF and SECOND_HALF auto-periods for the given month
   * across all organizations. Safe to call at any time — idempotent.
   */
  async seedPeriodsForMonth(year: number, month: number): Promise<void> {
    await this.generateForAllOrgs('FIRST_HALF', year, month);
    await this.generateForAllOrgs('SECOND_HALF', year, month);
  }

  // ── Core generation logic ─────────────────────────────────────────────────

  private async generateForAllOrgs(
    half: 'FIRST_HALF' | 'SECOND_HALF',
    year: number,
    month: number,
  ): Promise<void> {
    const orgs = await this.prisma.organization.findMany({
      where: { deletedAt: null },
      select: { id: true, tenantId: true },
    });

    const { startDate, endDate } = periodDates(half, year, month);

    let created = 0;
    let skipped = 0;

    for (const org of orgs) {
      try {
        const existing = await this.prisma.payrollPeriod.findFirst({
          where: {
            tenantId: org.tenantId,
            organizationId: org.id,
            startDate,
            endDate,
            deletedAt: null,
          },
          select: { id: true },
        });

        if (existing) {
          skipped++;
          continue;
        }

        await this.prisma.payrollPeriod.create({
          data: {
            tenantId: org.tenantId,
            organizationId: org.id,
            type: half,
            status: 'OPEN',
            startDate,
            endDate,
            // BUG-BM: every period carries a submission cutoff, so a late
            // submission can be recognised as one.
            cutoffDate: defaultPeriodCutoff(endDate),
            isAutoGenerated: true,
          },
        });

        created++;
      } catch (err: unknown) {
        this.logger.error(
          `Failed to auto-generate ${half} ${year}-${String(month + 1).padStart(2, '0')} period for org ${org.id}: ${(err as Error).message}`,
        );
      }
    }

    this.logger.log(
      `${half} ${year}-${String(month + 1).padStart(2, '0')}: created=${created} skipped=${skipped}`,
    );
  }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * BUG-BM: days after `endDate` that a timesheet may still be submitted before it
 * counts as late. One day of grace — the last day of a period is normally worked
 * in full, so an evening-of-the-last-day submission is not a late submission.
 */
export const PERIOD_CUTOFF_GRACE_DAYS = 1;

/**
 * BUG-BM: the cutoff applied to any period created without an explicit one —
 * end of the day `PERIOD_CUTOFF_GRACE_DAYS` after `endDate`. `endDate` is a
 * date-only column (midnight UTC), so the end of that day is the following
 * midnight less a millisecond.
 */
export function defaultPeriodCutoff(endDate: Date): Date {
  return new Date(endDate.getTime() + (PERIOD_CUTOFF_GRACE_DAYS + 1) * 86_400_000 - 1);
}

/** Computes ISO Date objects for a semi-monthly period (no time component). */
function periodDates(
  half: 'FIRST_HALF' | 'SECOND_HALF',
  year: number,
  month: number,
): { startDate: Date; endDate: Date } {
  if (half === 'FIRST_HALF') {
    return {
      startDate: new Date(Date.UTC(year, month, 1)),
      endDate: new Date(Date.UTC(year, month, 15)),
    };
  }
  // Last day of the month
  const lastDay = new Date(Date.UTC(year, month + 1, 0)).getUTCDate();
  return {
    startDate: new Date(Date.UTC(year, month, 16)),
    endDate: new Date(Date.UTC(year, month, lastDay)),
  };
}

/** Advances a (year, month) pair by `n` months, wrapping year correctly. */
function monthOffset(year: number, month: number, n: number): { year: number; month: number } {
  const d = new Date(Date.UTC(year, month + n, 1));
  return { year: d.getUTCFullYear(), month: d.getUTCMonth() };
}
